lecture3/hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("bohdan", views.bohdan, name="bohdan"),
    path("<str:name>", views.greet, name="greet")

    

]

lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('', admin.site.urls),
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('tasks/', include("tasks.urls")),
    path('ny/', include("newyear.urls"))

]

lecture3/newyear/urls.py
from django.urls import path

from . import views
urlpatterns = [
    path("", views.index, name="index")
]

lecture3/tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

lecture3/hello/models.py
from django.db import models

# Create your models here.

lecture3/newyear/models.py
from django.db import models

# Create your models here.

lecture3/tasks/models.py
from django.db import models

# Create your models here.

lecture3/hello/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def bohdan(request):
    return HttpResponse("<h1>Hello, Bohdan<h1>")

def greet(request, name):
    return render(request,"hello/greet.html", {
        "name": name.capitalize()

    })

lecture3/newyear/views.py
from django.shortcuts import render

import datetime 

# Create your views here.

def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear\index.html", {
        "newyear": now.month == 1 and now.day == 1,
        "todayis": now
        })

lecture3/tasks/views.py
from queue import PriorityQueue
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from django import forms


tasks = ["foo","bar","baz"]

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New task")
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=100)

# Create your views here.

def index(request):
    return render(request, "tasks/index.html", {

        "tasks": tasks

    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            tasks.append(task)
            return HttpResponseRedirect(reverse("tasks:index")) 
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })

    return render(request, "tasks/add.html", {
        "form": NewTaskForm
    })

lecture3/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello, {{name}}!</title>

    </head>
    <body>
        <h1>Hello, {{name}}!</h1>
    </body>

</html>

lecture3/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello!</title>

    </head>
    <body>
        <h1>Hello world!</h1>
    </body>

</html>

lecture3/hello/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello!</title>
        <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">

    </head>
    <body>
        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>

        {% endif %}

        {{todayis}}
    </body>

</html>

lecture3/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
        <h1>add task</h1>
<form action="{% url 'tasks:add' %}", method="post">
    {% csrf_token %}
    {{ form }}

    <input type="submit">
</form>

<a href="{% url 'tasks:index' %}">View tasks </a>
{% endblock %}

lecture3/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
        <ul>
        {% for task in tasks %}
            <li>{{task}}</li>
        {% empty %}
            <li>No tasks</li>
        {% endfor %}
        </ul>

<a href="{% url 'tasks:add' %}">Add a new task </a>

        {% endblock %}

lecture3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks!</title>

    </head>
    <body>

        Look at me it's a layout
        {% block body %}
        {% endblock %}
    </body>

</html>